name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Checkout project code (needed to run scripts)
      - uses: actions/checkout@v2
      # Prepare AWS credentials using OIDC provider (uses id-token and contents)
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-2
      # Prepare Docker image builder
      - uses: docker/setup-buildx-action@v1
      # Get ECR credentials
      - run: ./scripts/ecr_login.sh
      # Build and push tagged image
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/voquis/terraform-destroy-git-branch-builds:$GITHUB_REF_NAME
      # Build and push latest image
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/voquis/terraform-destroy-git-branch-builds:latest
